"""empty message

Revision ID: 83f4d29f182c
Revises: b10af61f065b
Create Date: 2025-04-30 18:42:31.113573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f4d29f182c'
down_revision = 'b10af61f065b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_user_from_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_from_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_from_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('planet_user_from_id_fkey', 'user', ['user_from_id'], ['id'])

    # ### end Alembic commands ###
